<?php

namespace Database\Seeders;

use App\Models\Patient;
use App\Models\Assurance;
use Illuminate\Database\Seeder;

class PatientSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Récupération des assurances disponibles
        $assurances = Assurance::pluck('id', 'code')->toArray();

        $ascomaId = $assurances['ASCOMA-CMR'] ?? null;
        $axaId    = $assurances['AXA-SANTE'] ?? null;
        $sanlamId = $assurances['SANLAM-SAHAM'] ?? null;
        $activaId = $assurances['ACTIVA-ASSUR'] ?? null;
        $chanasId = $assurances['CHANAS-ASSUR'] ?? null;
        $cnpsId   = $assurances['CNPS-CMR'] ?? null;

        $patients = [
            [
                'code_patient' => 'PAT-2026-0001',
                'nom' => 'EBOKE',
                'prenom' => 'Emmanuel',
                'genre' => 'M',
                'date_naissance' => '1988-05-14',
                'lieu_naissance' => 'Douala',
                'lieu_residence' => 'Akwa',
                'profession' => 'Comptable',
                'telephone' => '+237699001122',
                'telephone_whatsapp' => '+237699001122',
                'email' => 'emmanuel.eboke@gmail.com',
                'ville' => 'Douala',
                'groupe_sanguin' => 'O+',
                'est_assure' => true,
                'assurance_id' => $ascomaId,
                'matricule_assurance' => 'ASC-88902',
                'taux_couverture' => 80,
                'allergies' => 'Aucune',
                'antecedents_medicaux' => 'Gastrite chronique',
                'parametres' => ['poids' => 78, 'taille' => 178, 'tension' => '12/8', 'temperature' => 36.8, 'pouls' => 72],
            ],
            [
                'code_patient' => 'PAT-2026-0002',
                'nom' => 'NANGO',
                'prenom' => 'Thérèse',
                'genre' => 'F',
                'date_naissance' => '1995-11-20',
                'lieu_naissance' => 'Yaoundé',
                'lieu_residence' => 'Bonapriso',
                'profession' => 'Enseignante',
                'telephone' => '+237677334455',
                'telephone_whatsapp' => '+237677334455',
                'email' => 'therese.nango@yahoo.fr',
                'ville' => 'Douala',
                'groupe_sanguin' => 'A+',
                'est_assure' => true,
                'assurance_id' => $axaId,
                'matricule_assurance' => 'AXA-2024-99',
                'taux_couverture' => 80,
                'allergies' => 'Pénicilline',
                'antecedents_medicaux' => 'Crises d\'asthme légères',
                'parametres' => ['poids' => 62, 'taille' => 165, 'tension' => '11/7', 'temperature' => 37.0, 'pouls' => 75],
            ],
            [
                'code_patient' => 'PAT-2026-0003',
                'nom' => 'TCHATCHOU',
                'prenom' => 'Aubin',
                'genre' => 'M',
                'date_naissance' => '2001-02-10',
                'lieu_naissance' => 'Bafoussam',
                'lieu_residence' => 'Makepe',
                'profession' => 'Étudiant',
                'telephone' => '+237655889900',
                'telephone_whatsapp' => '+237655889900',
                'email' => 'aubin.tchatchou@gmail.com',
                'ville' => 'Douala',
                'groupe_sanguin' => 'B+',
                'est_assure' => false,
                'assurance_id' => null,
                'matricule_assurance' => null,
                'taux_couverture' => 0,
                'allergies' => 'Aspirine',
                'antecedents_medicaux' => 'Aucun',
                'parametres' => ['poids' => 70, 'taille' => 172, 'tension' => '12/8', 'temperature' => 36.5, 'pouls' => 68],
            ],
            [
                'code_patient' => 'PAT-2026-0004',
                'nom' => 'MAMPOUYA',
                'prenom' => 'Grace',
                'genre' => 'F',
                'date_naissance' => '1990-08-25',
                'lieu_naissance' => 'Douala',
                'lieu_residence' => 'Bonamoussadi',
                'profession' => 'Avocate',
                'telephone' => '+237690112233',
                'email' => 'grace.mampouya@cabinet.cm',
                'ville' => 'Douala',
                'groupe_sanguin' => 'O-',
                'est_assure' => true,
                'assurance_id' => $sanlamId,
                'matricule_assurance' => 'SAN-33412',
                'taux_couverture' => 70,
                'allergies' => 'AINS',
                'antecedents_medicaux' => 'Migraine chronique',
                'parametres' => ['poids' => 68, 'taille' => 168, 'tension' => '13/8', 'temperature' => 37.1, 'pouls' => 80],
            ],
            [
                'code_patient' => 'PAT-2026-0005',
                'nom' => 'EKOBO',
                'prenom' => 'Joseph',
                'genre' => 'M',
                'date_naissance' => '1975-03-12',
                'lieu_naissance' => 'Edea',
                'lieu_residence' => 'Deido',
                'profession' => 'Ingénieur',
                'telephone' => '+237670223344',
                'email' => 'j.ekobo@btp-cm.com',
                'ville' => 'Douala',
                'groupe_sanguin' => 'AB+',
                'est_assure' => true,
                'assurance_id' => $activaId,
                'matricule_assurance' => 'ACT-90811',
                'taux_couverture' => 80,
                'allergies' => 'Aucune',
                'antecedents_medicaux' => 'Hypertension Artérielle (HTA)',
                'parametres' => ['poids' => 85, 'taille' => 180, 'tension' => '14/9', 'temperature' => 36.7, 'pouls' => 78],
            ],
            [
                'code_patient' => 'PAT-2026-0006',
                'nom' => 'MBANGO',
                'prenom' => 'Chantal',
                'genre' => 'F',
                'date_naissance' => '1982-12-05',
                'lieu_naissance' => 'Douala',
                'lieu_residence' => 'Kotto',
                'profession' => 'Commerçante',
                'telephone' => '+237691334455',
                'ville' => 'Douala',
                'groupe_sanguin' => 'A-',
                'est_assure' => false,
                'assurance_id' => null,
                'matricule_assurance' => null,
                'taux_couverture' => 0,
                'allergies' => 'Sulfamides',
                'antecedents_medicaux' => 'Diabète de type 2',
                'parametres' => ['poids' => 82, 'taille' => 162, 'tension' => '13/8', 'temperature' => 36.9, 'pouls' => 74],
            ],
            [
                'code_patient' => 'PAT-2026-0007',
                'nom' => 'KOUAM',
                'prenom' => 'Patrick',
                'genre' => 'M',
                'date_naissance' => '1993-07-19',
                'lieu_naissance' => 'Dschang',
                'lieu_residence' => 'Logbessou',
                'profession' => 'Développeur Informatique',
                'telephone' => '+237650445566',
                'email' => 'patrick.kouam@tech.cm',
                'ville' => 'Douala',
                'groupe_sanguin' => 'O+',
                'est_assure' => true,
                'assurance_id' => $ascomaId,
                'matricule_assurance' => 'ASC-10293',
                'taux_couverture' => 80,
                'allergies' => 'Poussière / Acariens',
                'antecedents_medicaux' => 'Aucun',
                'parametres' => ['poids' => 73, 'taille' => 175, 'tension' => '12/7', 'temperature' => 36.6, 'pouls' => 65],
            ],
            [
                'code_patient' => 'PAT-2026-0008',
                'nom' => 'NJOH',
                'prenom' => 'Henriette',
                'genre' => 'F',
                'date_naissance' => '1968-04-30',
                'lieu_naissance' => 'Douala',
                'lieu_residence' => 'Bali',
                'profession' => 'Retraitée',
                'telephone' => '+237671556677',
                'ville' => 'Douala',
                'groupe_sanguin' => 'B-',
                'est_assure' => true,
                'assurance_id' => $cnpsId,
                'matricule_assurance' => 'CNPS-77821',
                'taux_couverture' => 100,
                'allergies' => 'Aucune',
                'antecedents_medicaux' => 'HTA, Arthrose du genou',
                'parametres' => ['poids' => 76, 'taille' => 160, 'tension' => '14/8', 'temperature' => 37.0, 'pouls' => 70],
            ],
            [
                'code_patient' => 'PAT-2026-0009',
                'nom' => 'BILOUNGA',
                'prenom' => 'Serge',
                'genre' => 'M',
                'date_naissance' => '1998-09-14',
                'lieu_naissance' => 'Ebolowa',
                'lieu_residence' => 'Ndogpassi',
                'profession' => 'Chauffeur',
                'telephone' => '+237692667788',
                'ville' => 'Douala',
                'groupe_sanguin' => 'O+',
                'est_assure' => false,
                'assurance_id' => null,
                'matricule_assurance' => null,
                'taux_couverture' => 0,
                'allergies' => 'Aucune',
                'antecedents_medicaux' => 'Ulcéreux',
                'parametres' => ['poids' => 69, 'taille' => 171, 'tension' => '11/8', 'temperature' => 36.7, 'pouls' => 72],
            ],
            [
                'code_patient' => 'PAT-2026-0010',
                'nom' => 'FOSSO',
                'prenom' => 'Marthe',
                'genre' => 'F',
                'date_naissance' => '2003-01-22',
                'lieu_naissance' => 'Bafang',
                'lieu_residence' => 'Cité des Palmiers',
                'profession' => 'Étudiante',
                'telephone' => '+237651778899',
                'email' => 'marthe.fosso@univ-douala.cm',
                'ville' => 'Douala',
                'groupe_sanguin' => 'AB-',
                'est_assure' => true,
                'assurance_id' => $chanasId,
                'matricule_assurance' => 'CHA-44120',
                'taux_couverture' => 80,
                'allergies' => 'Lactose',
                'antecedents_medicaux' => 'Aucun',
                'parametres' => ['poids' => 55, 'taille' => 163, 'tension' => '11/6', 'temperature' => 36.8, 'pouls' => 76],
            ],
            [
                'code_patient' => 'PAT-2026-0011',
                'nom' => 'SONG',
                'prenom' => 'Daniel',
                'genre' => 'M',
                'date_naissance' => '1984-06-11',
                'lieu_naissance' => 'Eséka',
                'lieu_residence' => 'Nyalla',
                'profession' => 'Ménagère / Artisan',
                'telephone' => '+237672889900',
                'ville' => 'Douala',
                'groupe_sanguin' => 'A+',
                'est_assure' => false,
                'assurance_id' => null,
                'matricule_assurance' => null,
                'taux_couverture' => 0,
                'allergies' => 'Iode',
                'antecedents_medicaux' => 'Lumbago à répétition',
                'parametres' => ['poids' => 81, 'taille' => 176, 'tension' => '12/8', 'temperature' => 36.9, 'pouls' => 71],
            ],
            [
                'code_patient' => 'PAT-2026-0012',
                'nom' => 'ABENA',
                'prenom' => 'Nathalie',
                'genre' => 'F',
                'date_naissance' => '1991-10-08',
                'lieu_naissance' => 'Akonolinga',
                'lieu_residence' => 'Bonabéri',
                'profession' => 'Infirmière',
                'telephone' => '+237693990011',
                'email' => 'nathalie.abena@sante.cm',
                'ville' => 'Douala',
                'groupe_sanguin' => 'O+',
                'est_assure' => true,
                'assurance_id' => $axaId,
                'matricule_assurance' => 'AXA-99102',
                'taux_couverture' => 80,
                'allergies' => 'Latex',
                'antecedents_medicaux' => 'Anémie passagère',
                'parametres' => ['poids' => 64, 'taille' => 167, 'tension' => '12/7', 'temperature' => 37.1, 'pouls' => 73],
            ],
            [
                'code_patient' => 'PAT-2026-0013',
                'nom' => 'KAMGA',
                'prenom' => 'Alain',
                'genre' => 'M',
                'date_naissance' => '1979-02-28',
                'lieu_naissance' => 'Mbouda',
                'lieu_residence' => 'Lendotti',
                'profession' => 'Pharmacien',
                'telephone' => '+237652001122',
                'email' => 'alain.kamga@pharma.cm',
                'ville' => 'Douala',
                'groupe_sanguin' => 'B+',
                'est_assure' => true,
                'assurance_id' => $sanlamId,
                'matricule_assurance' => 'SAN-88120',
                'taux_couverture' => 70,
                'allergies' => 'Aucune',
                'antecedents_medicaux' => 'Cholestérol élevé',
                'parametres' => ['poids' => 88, 'taille' => 179, 'tension' => '13/9', 'temperature' => 36.6, 'pouls' => 77],
            ],
            [
                'code_patient' => 'PAT-2026-0014',
                'nom' => 'DONFACK',
                'prenom' => 'Viviane',
                'genre' => 'F',
                'date_naissance' => '1997-05-17',
                'lieu_naissance' => 'Dschang',
                'lieu_residence' => 'Ndokoti',
                'profession' => 'Secrétaire',
                'telephone' => '+237673112233',
                'ville' => 'Douala',
                'groupe_sanguin' => 'O+',
                'est_assure' => false,
                'assurance_id' => null,
                'matricule_assurance' => null,
                'taux_couverture' => 0,
                'allergies' => 'Aucune',
                'antecedents_medicaux' => 'Aucun',
                'parametres' => ['poids' => 59, 'taille' => 162, 'tension' => '11/7', 'temperature' => 36.8, 'pouls' => 69],
            ],
            [
                'code_patient' => 'PAT-2026-0015',
                'nom' => 'TCHINDA',
                'prenom' => 'Bertrand',
                'genre' => 'M',
                'date_naissance' => '1986-11-03',
                'lieu_naissance' => 'Bafoussam',
                'lieu_residence' => 'Bessengue',
                'profession' => 'Comptable agréé',
                'telephone' => '+237694223344',
                'email' => 'bertrand.tchinda@audit.cm',
                'ville' => 'Douala',
                'groupe_sanguin' => 'A-',
                'est_assure' => true,
                'assurance_id' => $activaId,
                'matricule_assurance' => 'ACT-77123',
                'taux_couverture' => 80,
                'allergies' => 'Pénicilline',
                'antecedents_medicaux' => 'Aucun',
                'parametres' => ['poids' => 76, 'taille' => 174, 'tension' => '12/8', 'temperature' => 36.7, 'pouls' => 70],
            ],
            [
                'code_patient' => 'PAT-2026-0016',
                'nom' => 'NGA',
                'prenom' => 'Marie-Claire',
                'genre' => 'F',
                'date_naissance' => '1972-08-19',
                'lieu_naissance' => 'Mbalmayo',
                'lieu_residence' => 'Logbaba',
                'profession' => 'Institutrice',
                'telephone' => '+237653334455',
                'ville' => 'Douala',
                'groupe_sanguin' => 'O+',
                'est_assure' => true,
                'assurance_id' => $cnpsId,
                'matricule_assurance' => 'CNPS-99012',
                'taux_couverture' => 100,
                'allergies' => 'Aucune',
                'antecedents_medicaux' => 'Diabète gestationnel en 2005',
                'parametres' => ['poids' => 79, 'taille' => 165, 'tension' => '13/8', 'temperature' => 37.0, 'pouls' => 74],
            ],
            [
                'code_patient' => 'PAT-2026-0017',
                'nom' => 'GWEI',
                'prenom' => 'Franklin',
                'genre' => 'M',
                'date_naissance' => '1994-03-27',
                'lieu_naissance' => 'Bamenda',
                'lieu_residence' => 'Bonabéri',
                'profession' => 'Technicien Réseau',
                'telephone' => '+237674445566',
                'email' => 'franklin.gwei@net.cm',
                'ville' => 'Douala',
                'groupe_sanguin' => 'B-',
                'est_assure' => false,
                'assurance_id' => null,
                'matricule_assurance' => null,
                'taux_couverture' => 0,
                'allergies' => 'Poussière',
                'antecedents_medicaux' => 'Sinusite chronique',
                'parametres' => ['poids' => 72, 'taille' => 177, 'tension' => '12/7', 'temperature' => 36.5, 'pouls' => 67],
            ],
            [
                'code_patient' => 'PAT-2026-0018',
                'nom' => 'ETUNDI',
                'prenom' => 'Solange',
                'genre' => 'F',
                'date_naissance' => '1999-07-12',
                'lieu_naissance' => 'Kribi',
                'lieu_residence' => 'Japoma',
                'profession' => 'Graphiste',
                'telephone' => '+237695556677',
                'email' => 'solange.etundi@design.cm',
                'ville' => 'Douala',
                'groupe_sanguin' => 'O+',
                'est_assure' => true,
                'assurance_id' => $ascomaId,
                'matricule_assurance' => 'ASC-55102',
                'taux_couverture' => 80,
                'allergies' => 'Aucune',
                'antecedents_medicaux' => 'Kyste ovarien opéré',
                'parametres' => ['poids' => 61, 'taille' => 166, 'tension' => '11/8', 'temperature' => 36.9, 'pouls' => 72],
            ],
            [
                'code_patient' => 'PAT-2026-0019',
                'nom' => 'BOPDA',
                'prenom' => 'Thierry',
                'genre' => 'M',
                'date_naissance' => '1980-12-01',
                'lieu_naissance' => 'Bafoussam',
                'lieu_residence' => 'Yassa',
                'profession' => 'Entrepreneur',
                'telephone' => '+237654667788',
                'email' => 't.bopda@holdings.cm',
                'ville' => 'Douala',
                'groupe_sanguin' => 'A+',
                'est_assure' => true,
                'assurance_id' => $chanasId,
                'matricule_assurance' => 'CHA-88219',
                'taux_couverture' => 80,
                'allergies' => 'Aspirine',
                'antecedents_medicaux' => 'HTA modérée',
                'parametres' => ['poids' => 89, 'taille' => 182, 'tension' => '13/9', 'temperature' => 36.7, 'pouls' => 75],
            ],
            [
                'code_patient' => 'PAT-2026-0020',
                'nom' => 'SOH',
                'prenom' => 'Clarisse',
                'genre' => 'F',
                'date_naissance' => '2000-04-15',
                'lieu_naissance' => 'Douala',
                'lieu_residence' => 'Ndokoti',
                'profession' => 'Vendeuse',
                'telephone' => '+237675778899',
                'ville' => 'Douala',
                'groupe_sanguin' => 'O+',
                'est_assure' => false,
                'assurance_id' => null,
                'matricule_assurance' => null,
                'taux_couverture' => 0,
                'allergies' => 'Aucune',
                'antecedents_medicaux' => 'Aucun',
                'parametres' => ['poids' => 58, 'taille' => 160, 'tension' => '12/7', 'temperature' => 36.6, 'pouls' => 70],
            ],
        ];

        foreach ($patients as $data) {
            Patient::updateOrCreate(
                ['code_patient' => $data['code_patient']],
                $data
            );
        }
    }
}